name: Generate release data
description: Generate some data needed for the release like the tag
outputs:
  name:
    description: Release name
    value: ${{ steps.generate-data.outputs.name }}
  version:
    description: App version
    value: ${{ steps.generate-data.outputs.version }}
  tag:
    description: Tag to create
    value: ${{ steps.generate-data.outputs.tag }}
  release_notes:
    description: Release notes extracted from the changelog using the version output
    value: ${{ steps.generate-data.outputs.release_notes }}
  is_non_final_version:
    description: Whether the version is a non-final version (e.g. 1.0.0-alpha1)
    value: ${{ steps.generate-data.outputs.is_non_final_version }}
runs:
  using: "composite"
  steps:
    - id: generate-data
      shell: bash
      run: |
        changelog_file="CHANGELOG.md"
        
        version=$(grep "version = " app/build.gradle.kts | sed 's/version = //;s/[^0-9a-zA-Z.-]*//g')
        tag="v$version"
        name="Version $version"
        release_notes=$(awk -v ver="$version" ' /^#+ \[/ { if (p) { exit }; if ($2 == "["ver"]") { p=1; next} } p && NF ' "$changelog_file")
        if echo "$version" | grep -q '-'; then
          is_non_final_version=true
        else
          is_non_final_version=false
        fi
        
        echo "name [$name]"
        echo "version [$version]"
        echo "tag [$tag]"
        echo "is_non_final_version [$is_non_final_version]"
        echo "release_notes ==== START ===="
        echo $release_notes
        echo "release_notes ==== END ===="
        
        echo "name=$name" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "release_notes<<EOF-DELIMITER" >> $GITHUB_OUTPUT
        echo "$release_notes" >> $GITHUB_OUTPUT
        echo "EOF-DELIMITER" >> $GITHUB_OUTPUT
        echo "is_non_final_version=$is_non_final_version" >> $GITHUB_OUTPUT
