# Default v1.23.7 config file: https://github.com/detekt/detekt/blob/v1.23.7/detekt-core/src/main/resources/default-detekt-config.yml
build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

console-reports:
  active: false

output-reports:
  active: true

comments:
  active: true

complexity:
  active: true
  LongParameterList:
    functionThreshold: 10 # for compose
    ignoreDefaultParameters: true # for compose
  TooManyFunctions:
    ignoreAnnotatedFunctions: ['Preview'] # for compose previews

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true

naming:
  active: true
  FunctionNaming:
    ignoreAnnotated: ['Composable'] # for compose
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*' # for compose

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MaxLineLength:
    maxLineLength: 150
  MagicNumber:
    ignorePropertyDeclaration: true # for compose
    ignoreCompanionObjectPropertyDeclaration: true # for compose
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview'] # for compose previews
  NewLineAtEndOfFile:
    active: false

formatting:
  active: true
  ImportOrdering:
    active: false
  FinalNewline: # duplicate of NewLineAtEndOfFile
    active: false
  MaximumLineLength: # duplicate of MaxLineLength
    maxLineLength: 150

