name: Create release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate release data
        id: generate-release-data
        uses: ./.github/actions/generate-release-data
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.generate-release-data.outputs.tag }}
          name: ${{ steps.generate-release-data.outputs.name }}
          body: ""
