name: Create packages

on:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        os: [windows-2022, macos-12]
        include:
          - os: windows-2022
            ext: exe
          - os: macos-12
            ext: dmg
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Create package
        uses: gradle/gradle-build-action@v2.2.2
        with:
          arguments: |
            clean
            package
            -PdebugConfig=false
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          path: |
            ${{ github.workspace }}/app/build/compose/binaries/main/${{ matrix.ext }}/*.${{ matrix.ext }}
          retention-days: 1

