name: Create release

on:
  push:
    branches:
      - main

jobs:
  create-packages:
    name: Crete packages
    uses: ./.github/workflows/reusable-create-packages.yml
  create-release:
    name: Crete release
    needs: [create-packages]
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Generate release data
        id: generate-release-data
        uses: ./.github/actions/generate-release-data
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ghd-*
          path: .downloads/artifact/
          merge-multiple: true
      - name: Compress binaries
        run: |
          cd .downloads/artifact/
          find . '(' -type f -name "*.dmg" -o -name "*.exe" ')' -a -execdir zip '{}'.zip '{}' \;
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.generate-release-data.outputs.tag }}
          name: ${{ steps.generate-release-data.outputs.name }}
          body: "${{ steps.generate-release-data.outputs.release_notes }}"
          prerelease: ${{ steps.generate-release-data.outputs.is_non_final_version == 'true' }}
          files: |
            .downloads/artifact/*.dmg.zip
            .downloads/artifact/*.exe.zip
