name: Dependency updates

on:
  workflow_dispatch:

jobs:
  check-versions:
    name: Check versions
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2
      - name: Check dependency updates
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: |
            clean
            dependencyUpdates
            -PdebugConfig=false
      - name: Upload the report
        run: cat build/reports/dependencyUpdates/report.md > $GITHUB_STEP_SUMMARY
