name: Dependency updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1' # every Monday at 8:00

jobs:
  check-versions:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Setup and execute build and test Gradle tasks
        uses: gradle/gradle-build-action@v2.3.2
        with:
          arguments: |
            clean
            dependencyUpdates
            -PdebugConfig=false
      - name: Upload the report
        run: cat build/reports/dependencyUpdates/report.md > $GITHUB_STEP_SUMMARY
