name: Validations

on:
  workflow_dispatch:
  pull_request:

jobs:
  validations:
    name: Validations
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Generate release data
        id: generate-release-data
        uses: ./.github/actions/generate-release-data
      - name: Validate tag
        run: |
          git fetch --all --tags
          tag="${{ steps.generate-release-data.outputs.tag }}"
          exists=$(git tag -l "$tag")
          if [ -n "$exists" ]
          then
            echo "ERROR -> tag [$tag] found [$exists]"
            exit 1
          else
            echo "INFO -> the tag doesn't exist 👌"
          fi
      - name: Update 3rd party libraries JSON
        run: ./gradlew clean app:exportLibraryDefinitions -PaboutLibraries.exportPath=src/main/resources/
      - name: Validate 3rd party libraries JSON
        run: |
          if ! git diff --exit-code --quiet; then
            echo "ERROR -> 3rd party libraries JSON should be updated"
            exit 1
          fi
