name: Windows package

on:
  workflow_dispatch:

jobs:
  windows-package:
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Setup and execute package Gradle task
        uses: gradle/gradle-build-action@v2.2.2
        with:
          arguments: |
            clean
            package
            -PdebugConfig=false
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          path: |
            ${{ github.workspace }}/build/compose/binaries/main/exe/*.exe
          retention-days: 1
